version: '3.9'

services:
  backend:
    build: .
    command: gunicorn --worker-class gthread --threads 4 --bind 0.0.0.0:8000 backend.wsgi:app
    volumes:
      - .:/app
    environment:
      - FLASK_APP=backend.app:create_app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.27
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
